### ISSUE TITLE
Issue with Elysium portals

### ISSUE THREAD

**Issue by Sunconure11** [ata4/dragon-mounts#7]
When one attempts to use a portal from Elysium by right clicking on the dragon egg with a diamond, it instead starts the hatching process, breaking the portal.

**Comment by jredfox** [comment]
lol this is an incompatibility contact the Elysium to make them make a dragon egg block but you have to craft it with something different with the egg.

**Comment by ata4** [comment]
Hm yeah, when another mod adds a purpose to dragon egg blocks, things start to get a bit tricky... I could add an option to the config file to disable the block customization, but dragons then can only be created via console commands.

**Comment by jredfox** [comment]
why don't you just add an event if you right click with a diamond in the hand when Elysium mod is installed to light the portal ( only if the portal is built correctly) . I am more worried about orespawn since it makes it so that there will be more dragons at all.  Also backup plan for the Elysium is to make them spawn in only chests and make them a separate dragon egg block then to spawn the specified entities in the right conditions.

**Comment by Sunconure11** [comment]
I have a better idea.

Yes, we should have a different egg item, however, you should also be able to convert the enderdragon egg into a dragon mounts egg.

**Comment by Sunconure11** [comment]
Also, while this happened on KCauldron, you might want to look into this issue on 1.7.10:

https://github.com/ata4/dragon-mounts/issues/19

**Comment by jredfox** [comment]
or just do the advanced method and make it so that it is user friendly.  with changing it if you can't overided other mods overriding your mod to revert to only spawning in that one egg and I agree with the separate egg converter thing.  However that is exactly what I said except having to convert it you shouldn't have to convert it if you find it in a chest.  only use the converting method for the ender dragon egg if the egg method get's overided by incompatible mods.  Yes I don't even care I didn't use spellcheck I have other things to do .

**Comment by Sunconure11** [comment]
This has been resolved on later builds (1.9.4).
